# -*- coding: utf-8 -*-
"""AIML END EXAM.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1erz2Hw2p1TLcCm06el5VctLztAFS6Oeq
"""

#import the libraries
import pandas as pd
from sklearn.model_selection import train_test_split

#load the dataset
df=pd.read_csv('/content/fish.csv')
x=df[['livebait','xb','zg','camper']]
y=df['count']

#exploratary data analysis
print("shape of the dataset :",df.shape)
print("Five columns of dataset :\n",df.head())

# split into train and test
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=109)

# create the model
from sklearn import svm
clf=svm.SVC(kernel='linear')
clf.fit(x_train,y_train)

xtest=clf.predict(x_test)

from sklearn.metrics import accuracy_score,classification_report

print("Accuracy of the model is :",accuracy_score(y_test,xtest))
print("classification reort of the model is:",classification_report(y_test,xtest))