# -*- coding: utf-8 -*-
"""CIE3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cPfUaW3MEztKHBI_w1CAeI5mn1dROBgX
"""

import pandas as pd
df = pd.read_csv("/content/Boston_Housing (1).csv")
df.head

df.head()

df.info()

df.describe()

df.duplicated().sum()

df['AGE'].unique()

#spliting the data
import pandas as pd
from sklearn.model_selection import train_test_split
x=df['AGE']
y=df['ZN']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
print(x_train)
print(x_test)
print(y_train)
print(y_test)

import pandas as pd
data= pd.read_csv("/content/Iris.csv")
data.head

import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
iris=load_iris
data.head()

df.describe()

df['PetalLengthCm'].unique()

df.duplicated().sum()

#spliting the data
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score
data=load_iris()
x=data.data
y=data.target
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
from sklearn.tree import DecisionTreeClassifier
clf=DecisionTreeClassifier()
clf.fit(x_train,y_train)
y_pred=clf.predict(x_test)
print("Train data accuracy:",accuracy_score(y_true=y_train,y_pred=clf.predict(x_train)))
print("Train data accuracy:",accuracy_score(y_true=y_test,y_pred=y_pred))